---
- name: Create Ec2 instances
  hosts: localhost
  gather_facts: false
  collections:
  - amazon.aws
  module_defaults:
    group/aws:
      region: us-east-1
  tasks:
  # Block is a Group of Tasks combined together
  - name: Get Info Block
    block: 
      - name: Get Running instance Info
        ec2_instance_info:
        register: ec2info 
      - name: Print info
        debug: var="ec2info.instances"
             
  - name: Create EC2 Block
    block: 
      - name: Launch ec2 instances
        tags: create_ec2
        ec2_instance:
          region: us-east-1
          key_name: ralonsokey
          group: app_sec_group
          instance_type: t2.small
          image: ami-0c45afe2ce9bc14de
          wait: yes
          wait_timeout: 500
          count: 1
          instance_tags:
            name: appservers
            os: ubuntu
          monitoring: no
          vpc_subnet_id: subnet-0249d1541f0b2dc6d
          assign_public_ip: yes
        register: ec2
        delegate_to: localhost
      - name : Add instance to host group
        add_host:
          hostname: "{{ item.public_ip }}"
          groupname: launched
        loop: "{{ ec2.instances }}"
      - name: Wait for SSH to come up
        local_action:
          module: wait_for
          host: "{{ item.public_ip }}"
          port: 22
          delay: 10
          timeout: 120
        loop: "{{ ec2.instances }}"
