---
- name: Create Ec2 instances
  hosts: localhost
  gather_facts: false
  collections:
  - amazon.aws
  module_defaults:
    group/aws:
      region: us-east-1
  tasks:
  # Block is a Group of Tasks combined together
  - name: Get Info Block
    block: 
      - name: Get Running instance Info
        ec2_instance_info:
        register: ec2info 
      - name: Print info
        debug: var="ec2info.instances"
             
  - name: Create EC2 Block
    block: 
      - name: Launch ec2 instances
        ec2_instance:
          name: "{{ instance_name }}"
          region: us-east-1
          key_name: ralonsokey
          instance_type: t2.small
          image_id: "{{ image_id }}"
          wait: yes
          tags:
            Environment: dev
          wait_timeout: 500
          count: 1
          security_group: default
          vpc_subnet_id: subnet-0249d1541f0b2dc6d
          network:
            assign_public_ip: yes
        register: ec2
        delegate_to: localhost
      - name: Wait for SSH to come up
        local_action:
          module: wait_for
          host: "{{ item.public_ip }}"
          port: 22
          delay: 10
          timeout: 120
        loop: "{{ ec2.instances }}"
      - name: print public ip
        debug:
          msg: "Instance IP: {{ item.public_ip }}"
        loop: "{{ ec2.instances }}"
